name: CI de Pruebas Unitarias
on: [push, pull_request]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: |
          pip install pytest pytest-cov
      - name: Ejecutar Pruebas y Validar Cobertura
        # Este comando busca los archivos en cualquier subcarpeta automáticamente
        run: python -m pytest --cov=. --cov-fail-under=80
